### ISSUE TITLE
The reservation acceptance/rejection process must be simplified.

### ISSUE THREAD

**Issue by DiegoAstiazaran** [ProyectoIntegrador2018/makers#194]
## Task Title

The reservation acceptance/rejection process should be simplified.

### Description

Right now, in order to accept a reservation, the admin has to go to the edit page and select the new status. This action should be done from the same dashboard where all the reservations are listed.

### List of sub-tasks

- [ ] Add an option to change the status in the list of reservations.

### Definition of Done

- [ ] The general quality of the project has been improved
- [ ] The task's description has been accomplished
