### ISSUE TITLE
Remove the reservation status option rejected or canceled.

### ISSUE THREAD

**Issue by DiegoAstiazaran** [ProyectoIntegrador2018/makers#195]
## Task Title

Remove the reservation status option rejected or canceled.

### Description

There are several status options for a reservation. _Rejected_ and _canceled_ can be confused so one of them should be deleted.

### List of sub-tasks

- [ ] Remove one of the two status options mentioned.

### Definition of Done

- [ ] The general quality of the project has been improved
- [ ] The task's description has been accomplished
