### ISSUE TITLE
Set up environments

### ISSUE THREAD

**Issue by anakarenbm** [ProyectoIntegrador2018/makers#29]
Hacer el set up para tener diferentes ambientes, revisiones de código y utilizar Continuous Integration. 

## Tasks
- [x] Set up Heroku Staging Environment
- [x] Set up Heroku Production Environment
- [x] Set up [CI for Heroku](https://devcenter.heroku.com/articles/pipelines)
- [x] Install [Code Climate](https://codeclimate.com/) to our github repo

## Criterios de terminación
- [x] Opening a pull-request will run checks with Code Climate
- [x] Pushing to master will update the Staging App
- [x] You can "promote" your Staging app to Production with Heroku
