### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by anakarenbm** [ProyectoIntegrador2018/makers#30]
Mantener todos los documentos del proyetco actualizados a lo largo del sprint.

## Tasks
- [x] Crear documento DEPLOYMENT.md
- [x] Crear documento de la administración del proyecto (Reporte de minutas)
- [x] Crear Manual de Usuario
- [x] Actualizar doc de especificación del diseño
- [x] Actualizar doc de especificación de pruebas
