### ISSUE TITLE
Actualización de documentación

### ISSUE THREAD

**Issue by anakarenbm** [ProyectoIntegrador2018/makers#33]
Mantener todos los documentos del proyetco actualizados a lo largo del sprint.

## Tasks

- [x]  Actualizar documento DEPLOYMENT.md
- [x]  Actualizar documento de la administración del proyecto (Reporte de minutas)
- [x]  Actualizar Manual de Usuario
- [x]  Actualizar doc de especificación del diseño
- [x]  Actualizar doc de especificación de pruebas
