### ISSUE TITLE
S16 Como Usuario puedo visualizar todo el equipo de laboratorio existente de un laboratorio

### ISSUE THREAD

**Issue by hecerinc** [ProyectoIntegrador2018/makers#8]
# S16

**Prioridad:** 16

Como usuario puedo visualizar todo el equipo de laboratorio existente de un laboratorio para ver la oferta.

## Conversación
- No necesita haber iniciado sesión el usuario para ver el catálogo.

## To Do
- [x] Definir vista o vistas del flujo
- [x] Implementar vistas
- [x] Implementar funciones en controlador

## Criterios de aceptación
- [x] Se despliega el catálogo del equipo disponible para un laboratorio.
