### ISSUE TITLE
S026 Como usuario puedo editar mi información/perfil

### ISSUE THREAD

**Issue by anakarenbm** [ProyectoIntegrador2018/makers#88]
Como usuario puedo ver mi información en la sección de "Profile".

## Conversación
Quiero poder tener toda mi actividad e información en una misma sección y poder modificarla.

## Criterios de terminación
- [ ] El usuario tiene un perfil
- [ ] El usuario puede visualizar su información
- [ ] El usuario puede realizar cambios a su información

## Tasks
- [ ] Definir wireframes
- [ ] Definir conetnido en el User Profile
- [ ] Implementar las vistas/flujo en el frontend
- [ ] Implementar las acciones necesarias en el backend
